FROM registry.nimasfl.ir/sdm-backend-dep:prod as DEP
FROM registry.nimasfl.ir/node-alpine:14

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000

COPY package.json .
COPY --from=DEP /app/node_modules /app/node_modules
COPY src src
COPY nest-cli.json .
COPY .eslintrc.js .
COPY tsconfig.build.json .
COPY tsconfig.json .
COPY test test

#RUN npm run test:all
RUN npm run build
RUN rm -rf src
EXPOSE 3000
CMD [ "npm", "run", "start"]
