FROM node:lts-alpine

RUN mkdir -p /app
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000

COPY package.json .
RUN npm install --quiet --no-progress

COPY src src
COPY nest-cli.json .
COPY .eslintrc.js .
COPY tsconfig.build.json .
COPY tsconfig.json .
COPY test test

#RUN npm run test:all
RUN npm run build
RUN rm -rf src
EXPOSE 3000
CMD [ "npm", "run", "start"]
